---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Creating user accounts with useradd
    - name: module-02
      label: Setting the Account Password
    - name: module-03
      label: Adding Groups
    - name: module-04
      label: Removing a user for a group
    - name: module-05
      label: Removing Users
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
